#testing this CI yml file, ti should run thetesting stuff for me
#automatically, specifically on a push
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
      #download repo into github runner
        uses: actions/checkout@v4

      - name: Set up Node.js
      #install node in github
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Run lint
        run: npm run lint

      - name: Run production build
        run: npm run build